### ISSUE TITLE
Bug: Error When Using Plugin in Non-Admin Panels

### ISSUE THREAD

**Issue by edeoliv** [tomatophp/filament-alerts#4]
I'm encountering an error when using the plugin in any panel other than the admin panel. The error occurs specifically when I try to use the plugin in a custom panel that I created for my SaaS application.

I have three panels in my application:

Admin Panel (owner)
Dashboard Panel
Personal Panel

The issue arises in the Dashboard Panel, which is defined as follows:

```php

class DashboardPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('dashboard')
            ->path('dashboard');
    }
}

```
Steps to Reproduce:

1. Create multiple panels in a SaaS application (e.g., admin, dashboard, personal).
2. Attach the plugin to a non-admin panel (e.g., dashboard).
3. Attempt to use the plugin in the dashboard panel.

Expected Behavior:

The plugin should work seamlessly across all panels, not just in the admin panel.

Actual Behavior:

The plugin generates an error when used in any panel other than the admin panel.

Additional Information:

Panel ID where the issue occurs: dashboard
The plugin works fine in the admin panel.

![imagen](https://github.com/user-attachments/assets/4baf2d44-2d37-4a6e-8382-9465ab0c2801)
![imagen](https://github.com/user-attachments/assets/1808d81a-2825-4d74-ad4d-2be06ce0f00c)
![imagen](https://github.com/user-attachments/assets/a40968ca-df91-4aec-ae19-1708c156c6bc)

**Comment by 3x1io** [comment]
hi @edeoliv thanks for your report we will fix that ASAP.

**Comment by 3x1io** [comment]
fixed in last version.
